a = int(input("Please enter number 1 "))
b = int(input("Please enter number 2 "))

print("Addition is ", a+b)
print("Subtraction is ", a-b)
print("Myltiplication is ", a*b)
print("DiVision is ", a/b)
print("Exponentiation is ", a**b)
print("Floor division is ", a//b)
print("Modulus is ", a%b)